#!/bin/bash

echo "How many number of terms to be generated?"

read n
function fib
x = 0
y = 1
i = 2
echo "Fibonacci Series up to Sn terms"
echo "$x"
echo "$y"
while [$i-It $n]
do
i=` expr$i +1`
z='expr $x + $y`
echo "$z" 
x =$y
y=$z
done
}
r=` fib $n`
echo "$r"
